---
title: "Assignment-QMM"
author: "Ashvitha Mothakani"
date: '2022-10-19'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}

#Assignment 
#MODULE 6
#THE TRANSPORTATION MODEL

#Objective function: 
#Minimize the combined cost of production and shipping
#Min = 22x11 + 14x12 + 30x13+ 16x21 + 20x22+ 24x23
#Subject to :
#x11 + x12 + x13\le 100 ( For Plant A)
#x21 + x22 + x23\geq 120 (For Plant B)
#Constraints :
#Demand Constraints 
#Warehouse 1: x11 + x21 \geq 80
#Warehouse 2: x12 + x22 \geq 60
#Warehouse 3: x13 + x23 \geq 70

#As we can see this transportation problem is unbalanced. Since demand < supply by 10.

#I am using the dummy variable method. Where I created a dummy variable in column 4 with
#the transportation cost = 0 and demand = 10.

#solving transportation problem in R

library(Matrix)
library(lpSolve)

```



```{r cars}

#THE TRANSPORTATION MODEL

#Objective function: 
#Minimize the combined cost of production and shipping
#Min = 22x11 + 14x12 + 30x13+ 16x21 + 20x22+ 24x23
#Subject to :
#x11 + x12 + x13\le 100 ( For Plant A)
#x21 + x22 + x23\geq 120 (For Plant B)
#Constraints :
#Demand Constraints 
#Warehouse 1: x11 + x21 \geq 80
#Warehouse 2: x12 + x22 \geq 60
#Warehouse 3: x13 + x23 \geq 70

#As we can see this transportation problem is unbalanced. Since demand < supply by 10.

#I am using the dummy variable method. Where I created a dummy variable in column 4 with
#the transportation cost = 0 and demand = 10.

#solving transportation problem in R

#writing down the costs

costs <- matrix(c(622,614,630,0,
                  641,645,649,0), ncol = 4, byrow = TRUE)


#set up constraints signs and right hand sides 

colnames(costs) <- c("Warehouse1", "Warehouse2", "WAREHOUSE3", "Dummy")
row.names(costs) <- c("PlantA", "PLantB")
costs <- as.table(costs)
costs

#the Production Capacity in the row of the matrix:
#supply side

row.signs <- rep("<=", 2)
row.rhs <- c(100,120)

#the Monthly Demand with double variable of 10 at the end. Above we added the 0,0
#in at the end of each of the columns:
#demand side

col.signs <- rep(">=", 4)
col.rhs <- c(80,60,70,10)

#we are ready to run LP Transport command:

lptrans <- lp.transport(costs, "min", row.signs, row.rhs, col.signs, col.rhs)

#values of all variables

lptrans$solution

#values of the objective function

lptrans$objval

#the objective function answer is 132790

#economic interpretation of the dual

lptrans$duals

#the dual is nothing but the shadow prices of primal. Therefore the answer comes out to be zero.
#Marginal revenue = Marginal cost.
#the dual solution is nothing more than the shadow pricing of the primal. 
#The dual solution of this problem indicates that all of the shadow prices for
#the primary problem are equal to zero. #This signifies that there is no way to 
#improve profit or lower cost by reallocating resources (the outcome we have concluded is 
#the realistic answer)in this situation marginal revenue equals marginal cost.

```



